name: CICD Frontend and Backend

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker frontend image
        run: docker build -t drivesmart/drivesmart-admin .
      - name: Publish frontend image to Docker Hub
        run: docker push drivesmart/drivesmart-admin

 

  deploy:
    needs: [build-frontend]
    runs-on: aws-ec2
    steps:
      - name: Pull frontend image from Docker Hub
        run: docker pull drivesmart/drivesmart-admin
      - name: Delete old frontend container
        run: docker rm -f drivesmart-admin-container
      - name: Run frontend container
        run: docker run -d -p 8000:8000 --name drivesmart-admin-container drivesmart/drivesmart-admin
    
